import type { DirectoryAgent } from "./types";

export const SEED_AGENTS: readonly DirectoryAgent[] = [
  // ─── Keepers ────────────────────────────────────────────────────────────
  {
    address: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
    chainId: "ethereum",
    name: "ERC-4337 EntryPoint",
    agentType: "KEEPER",
    score: 92,
    recommendation: "SAFE",
    behavioralNarrative: "Core account abstraction infrastructure. Processes UserOps with extreme regularity — 14k+ daily transactions, near-zero downtime since deployment.",
    financialSummary: { totalGasSpentETH: "284.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.98 },
    protocolsUsed: ["ERC-4337", "Bundler Network"],
    funFact: "Processes more transactions than most L2s combined.",
    anomalies: [],
    txCount: 892341,
    lastActive: Date.now() - 12000,
    source: "seed",
  },
  {
    address: "0x02777053d6764996e594c3E88AF1D58D5363a2e6",
    chainId: "ethereum",
    name: "Chainlink Automation Registry v2.1",
    agentType: "KEEPER",
    score: 95,
    recommendation: "SAFE",
    behavioralNarrative: "Decentralized automation network executing upkeep tasks. Highly consistent timing patterns with multi-node redundancy.",
    financialSummary: { totalGasSpentETH: "1204.3", netFlowETH: "+12.8" },
    operationalPattern: { peakHoursUTC: [10, 11, 14, 15], consistencyScore: 0.97 },
    protocolsUsed: ["Chainlink Automation", "Chainlink Keepers"],
    funFact: "Has never missed a critical upkeep since v2.1 launch.",
    anomalies: [],
    txCount: 1456782,
    lastActive: Date.now() - 8000,
    source: "seed",
  },
  {
    address: "0x29b6603D17B9D8f021EcB8845B6FD06E1Adf89DE",
    chainId: "ethereum",
    name: "Gelato Automate",
    agentType: "KEEPER",
    score: 89,
    recommendation: "SAFE",
    behavioralNarrative: "Web3 automation relay executing scheduled tasks and conditional transactions. Operates across multiple chains with gasless relay support.",
    financialSummary: { totalGasSpentETH: "421.6", netFlowETH: "+3.2" },
    operationalPattern: { peakHoursUTC: [12, 13, 16, 17], consistencyScore: 0.94 },
    protocolsUsed: ["Gelato Network", "Gelato Relay"],
    funFact: "Processes automation tasks for 400+ DeFi protocols.",
    anomalies: [],
    txCount: 672109,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0x0048a99770E1fF60c40aDa7863b2E30E1F23538b",
    chainId: "base",
    name: "Keep3r V2 Job Registry",
    agentType: "KEEPER",
    score: 82,
    recommendation: "SAFE",
    behavioralNarrative: "Keeper network job coordination. Moderate activity with consistent execution patterns across registered jobs.",
    financialSummary: { totalGasSpentETH: "18.4", netFlowETH: "+0.9" },
    operationalPattern: { peakHoursUTC: [8, 9, 20, 21], consistencyScore: 0.88 },
    protocolsUsed: ["Keep3r V2"],
    funFact: "Andre Cronje's original keeper network — still running.",
    anomalies: [],
    txCount: 34521,
    lastActive: Date.now() - 45000,
    source: "seed",
  },
  // ─── Oracles ────────────────────────────────────────────────────────────
  {
    address: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419",
    chainId: "ethereum",
    name: "Chainlink ETH/USD Price Feed",
    agentType: "ORACLE",
    score: 97,
    recommendation: "SAFE",
    behavioralNarrative: "Primary ETH/USD price oracle. Updates with heartbeat precision — deviation threshold triggers within seconds. Backbone of DeFi pricing.",
    financialSummary: { totalGasSpentETH: "892.1", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.99 },
    protocolsUsed: ["Chainlink", "Chainlink Price Feeds"],
    funFact: "Secures over $20B in DeFi TVL with a single price feed.",
    anomalies: [],
    txCount: 2891034,
    lastActive: Date.now() - 3000,
    source: "seed",
  },
  {
    address: "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C",
    chainId: "ethereum",
    name: "Pyth Network Price Pusher",
    agentType: "ORACLE",
    score: 88,
    recommendation: "SAFE",
    behavioralNarrative: "Pull-based oracle pushing Pyth price updates on-demand. Bursty activity aligned with market volatility spikes.",
    financialSummary: { totalGasSpentETH: "156.3", netFlowETH: "-2.1" },
    operationalPattern: { peakHoursUTC: [13, 14, 15, 20], consistencyScore: 0.85 },
    protocolsUsed: ["Pyth Network", "Wormhole"],
    funFact: "Activity correlates 0.94 with VIX — busier when markets panic.",
    anomalies: [],
    txCount: 489201,
    lastActive: Date.now() - 22000,
    source: "seed",
  },
  {
    address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
    chainId: "ethereum",
    name: "Lido wstETH Oracle Reporter",
    agentType: "ORACLE",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "Reports stETH exchange rate updates from Lido oracle committee. Predictable daily cadence with multi-sig oracle consensus.",
    financialSummary: { totalGasSpentETH: "67.2", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [12, 13], consistencyScore: 0.96 },
    protocolsUsed: ["Lido", "Lido Oracle"],
    funFact: "Updates exactly once per day — the most punctual agent in DeFi.",
    anomalies: [],
    txCount: 12890,
    lastActive: Date.now() - 60000,
    source: "seed",
  },
  {
    address: "0x47Fb2585D2C56Fe188D0E6ec628a38b74fCeeeDf",
    chainId: "ethereum",
    name: "UMA Optimistic Oracle",
    agentType: "ORACLE",
    score: 84,
    recommendation: "SAFE",
    behavioralNarrative: "Dispute-based oracle resolving arbitrary data requests. Activity spikes during governance votes and insurance claim periods.",
    financialSummary: { totalGasSpentETH: "34.8", netFlowETH: "+1.2" },
    operationalPattern: { peakHoursUTC: [15, 16, 17], consistencyScore: 0.79 },
    protocolsUsed: ["UMA Protocol", "Polymarket"],
    funFact: "Powered every Polymarket election prediction in 2024.",
    anomalies: [],
    txCount: 89102,
    lastActive: Date.now() - 180000,
    source: "seed",
  },
  // ─── Bridge Relayers ────────────────────────────────────────────────────
  {
    address: "0x5c7BCd6E7De5423a257D81B442095A1a6ced35C5",
    chainId: "ethereum",
    name: "Across Protocol Relayer",
    agentType: "BRIDGE_RELAYER",
    score: 86,
    recommendation: "SAFE",
    behavioralNarrative: "Optimistic bridge relayer fulfilling cross-chain intents. High-value transfers with rapid finality — typically 2-10 seconds for most routes.",
    financialSummary: { totalGasSpentETH: "312.4", netFlowETH: "+89.3" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.91 },
    protocolsUsed: ["Across Protocol", "UMA"],
    funFact: "Relays more volume per dollar of gas than any other bridge.",
    anomalies: [],
    txCount: 234891,
    lastActive: Date.now() - 5000,
    source: "seed",
  },
  {
    address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
    chainId: "polygon",
    name: "Stargate Finance Relayer",
    agentType: "BRIDGE_RELAYER",
    score: 83,
    recommendation: "SAFE",
    behavioralNarrative: "LayerZero-based bridge relayer executing cross-chain swaps via unified liquidity pools. Consistent volume across 8+ chains.",
    financialSummary: { totalGasSpentETH: "78.9", netFlowETH: "+24.6" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 22], consistencyScore: 0.87 },
    protocolsUsed: ["Stargate", "LayerZero"],
    funFact: "Moves USDC between chains faster than most CEX withdrawals.",
    anomalies: [],
    txCount: 156234,
    lastActive: Date.now() - 30000,
    source: "seed",
  },
  {
    address: "0x3154Cf16ccdb4C6d922629664174b904d80F2C35",
    chainId: "base",
    name: "Base Bridge Operator",
    agentType: "BRIDGE_RELAYER",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "Official Base L1→L2 message relayer. Processes deposits and withdrawals with Optimism Bedrock finality guarantees.",
    financialSummary: { totalGasSpentETH: "523.1", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.95 },
    protocolsUsed: ["OP Stack", "Base Bridge"],
    funFact: "Processes $2M+ in daily bridge volume for Coinbase users.",
    anomalies: [],
    txCount: 891023,
    lastActive: Date.now() - 7000,
    source: "seed",
  },
  {
    address: "0xaBEA9132b05A70803a4E85094fD0e1800777fBEF",
    chainId: "arbitrum",
    name: "Hop Protocol Bonder",
    agentType: "BRIDGE_RELAYER",
    score: 80,
    recommendation: "SAFE",
    behavioralNarrative: "Liquidity bonder providing instant cross-chain transfers by fronting assets. Moderate risk tolerance with bonded collateral backing.",
    financialSummary: { totalGasSpentETH: "145.2", netFlowETH: "+31.7" },
    operationalPattern: { peakHoursUTC: [13, 14, 19, 20], consistencyScore: 0.83 },
    protocolsUsed: ["Hop Protocol"],
    funFact: "One of the earliest bridge bonders — active since Arbitrum launch.",
    anomalies: [],
    txCount: 67234,
    lastActive: Date.now() - 120000,
    source: "seed",
  },
  // ─── Liquidators ────────────────────────────────────────────────────────
  {
    address: "0x80226Fc0Ee2b096224EeAc085Bb9a8cba1146f7D",
    chainId: "ethereum",
    name: "Aave V3 Liquidation Bot",
    agentType: "LIQUIDATOR",
    score: 74,
    recommendation: "CAUTION",
    behavioralNarrative: "Aggressive liquidation bot targeting undercollateralized Aave V3 positions. Spikes during market downturns — 40x normal volume during crash events.",
    financialSummary: { totalGasSpentETH: "89.4", netFlowETH: "+234.8" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.62 },
    protocolsUsed: ["Aave V3", "Flashbots"],
    funFact: "Earned 234 ETH profit during the March 2024 liquidation cascade.",
    anomalies: ["Burst activity: 400+ txns in 10 minutes during market stress"],
    txCount: 45123,
    lastActive: Date.now() - 90000,
    source: "seed",
  },
  {
    address: "0xc3D688B66703497DAA19211EEdff47f25384cdc3",
    chainId: "ethereum",
    name: "Compound V3 Absorber",
    agentType: "LIQUIDATOR",
    score: 78,
    recommendation: "CAUTION",
    behavioralNarrative: "Compound III absorber bot converting underwater positions. Methodical approach — queues positions by health factor and liquidates in batches.",
    financialSummary: { totalGasSpentETH: "34.2", netFlowETH: "+67.1" },
    operationalPattern: { peakHoursUTC: [8, 9, 14, 15], consistencyScore: 0.71 },
    protocolsUsed: ["Compound V3"],
    funFact: "Batches liquidations to save 30% on gas vs individual calls.",
    anomalies: [],
    txCount: 23891,
    lastActive: Date.now() - 200000,
    source: "seed",
  },
  {
    address: "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e",
    chainId: "ethereum",
    name: "Aave V3 Pool Liquidator",
    agentType: "LIQUIDATOR",
    score: 71,
    recommendation: "CAUTION",
    behavioralNarrative: "Secondary Aave liquidator operating with Flashbots bundles. Lower latency competitor — occasionally front-runs primary liquidators via MEV.",
    financialSummary: { totalGasSpentETH: "56.8", netFlowETH: "+112.4" },
    operationalPattern: { peakHoursUTC: [2, 3, 14, 15], consistencyScore: 0.58 },
    protocolsUsed: ["Aave V3", "Flashbots", "MEV-Boost"],
    funFact: "Uses MEV-Boost to guarantee inclusion — never gets reverted.",
    anomalies: ["MEV bundle usage for liquidation front-running"],
    txCount: 31209,
    lastActive: Date.now() - 150000,
    source: "seed",
  },
  // ─── MEV Bots ───────────────────────────────────────────────────────────
  {
    address: "0x56178a0d5F301bAf6CF3e1Cd53d9863437345Bf9",
    chainId: "ethereum",
    name: "MEV Bot: Sandwich Hunter",
    agentType: "MEV_BOT",
    score: 31,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Aggressive sandwich attacker targeting large DEX swaps. Front-runs and back-runs victim transactions in atomic bundles. Extracted 890 ETH in 90 days.",
    financialSummary: { totalGasSpentETH: "234.5", netFlowETH: "+890.2" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.45 },
    protocolsUsed: ["Uniswap V2", "Uniswap V3", "Flashbots"],
    funFact: "This bot has sandwiched more retail traders than any NYC deli.",
    anomalies: ["Sandwich attack pattern detected", "Targets swaps > 10 ETH"],
    txCount: 234891,
    lastActive: Date.now() - 4000,
    source: "seed",
  },
  {
    address: "0x00000000000747D525E898A17AE89C6800FF3Cf2",
    chainId: "ethereum",
    name: "MEV Bot: JIT Liquidity",
    agentType: "MEV_BOT",
    score: 52,
    recommendation: "CAUTION",
    behavioralNarrative: "Just-in-time liquidity provider. Adds concentrated liquidity milliseconds before large swaps, captures fees, removes immediately after.",
    financialSummary: { totalGasSpentETH: "167.3", netFlowETH: "+412.8" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.39 },
    protocolsUsed: ["Uniswap V3", "Flashbots"],
    funFact: "Provides better execution for traders while extracting MEV — a rare win-win.",
    anomalies: ["JIT liquidity manipulation detected"],
    txCount: 178923,
    lastActive: Date.now() - 6000,
    source: "seed",
  },
  {
    address: "0xA69babEF1cA67A37Ffaf7a485DfFF3382056e78C",
    chainId: "ethereum",
    name: "MEV Bot: Backrunner",
    agentType: "MEV_BOT",
    score: 44,
    recommendation: "CAUTION",
    behavioralNarrative: "Opportunistic backrunner exploiting arbitrage created by large swaps. Less harmful than sandwich bots but still extracts value from orderflow.",
    financialSummary: { totalGasSpentETH: "89.1", netFlowETH: "+201.4" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.52 },
    protocolsUsed: ["Uniswap V2", "SushiSwap", "Flashbots"],
    funFact: "Failed 34% of its transactions — the cost of doing MEV.",
    anomalies: ["High revert rate: 34%"],
    txCount: 145672,
    lastActive: Date.now() - 18000,
    source: "seed",
  },
  // ─── DEX Traders ────────────────────────────────────────────────────────
  {
    address: "0x1111111254EEB25477B68fb85Ed929f73A960582",
    chainId: "ethereum",
    name: "1inch Aggregation Router V5",
    agentType: "DEX_TRADER",
    score: 93,
    recommendation: "SAFE",
    behavioralNarrative: "Major DEX aggregator routing trades across 50+ liquidity sources. Optimizes execution by splitting orders across multiple pools.",
    financialSummary: { totalGasSpentETH: "1891.2", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.93 },
    protocolsUsed: ["1inch", "Uniswap V3", "Curve", "Balancer"],
    funFact: "Routes through an average of 3.2 pools per trade for best execution.",
    anomalies: [],
    txCount: 3456789,
    lastActive: Date.now() - 2000,
    source: "seed",
  },
  {
    address: "0xDef1C0ded9bec7F1a1670819833240f027b25EfF",
    chainId: "ethereum",
    name: "0x Exchange Proxy",
    agentType: "DEX_TRADER",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "0x Protocol exchange proxy aggregating RFQ and AMM liquidity. Powers Matcha and many DeFi frontends with gasless limit orders.",
    financialSummary: { totalGasSpentETH: "923.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 19, 20], consistencyScore: 0.91 },
    protocolsUsed: ["0x Protocol", "Uniswap V3", "Curve"],
    funFact: "Supports gasless limit orders — users trade without paying gas.",
    anomalies: [],
    txCount: 2891023,
    lastActive: Date.now() - 9000,
    source: "seed",
  },
  {
    address: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
    chainId: "ethereum",
    name: "Uniswap V3 SwapRouter",
    agentType: "DEX_TRADER",
    score: 96,
    recommendation: "SAFE",
    behavioralNarrative: "Core Uniswap V3 routing contract. Processes single-hop and multi-hop swaps with concentrated liquidity. The heartbeat of onchain trading.",
    financialSummary: { totalGasSpentETH: "4521.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.96 },
    protocolsUsed: ["Uniswap V3"],
    funFact: "Has facilitated over $1T in cumulative swap volume.",
    anomalies: [],
    txCount: 12345678,
    lastActive: Date.now() - 1000,
    source: "seed",
  },
] as const;

/** Mapping from AgentType to display name */
export const AGENT_TYPE_LABELS: Record<string, string> = {
  KEEPER: "Keepers",
  ORACLE: "Oracles",
  BRIDGE_RELAYER: "Bridge Relayers",
  LIQUIDATOR: "Liquidators",
  MEV_BOT: "MEV Bots",
  DEX_TRADER: "DEX Traders",
  UNKNOWN: "Unknown",
};

/** Mapping from AgentType to donut/label color */
export const AGENT_TYPE_COLORS: Record<string, string> = {
  KEEPER: "#22c55e",
  ORACLE: "#6ea8fe",
  BRIDGE_RELAYER: "#9070d4",
  LIQUIDATOR: "#eab308",
  MEV_BOT: "#ef4444",
  DEX_TRADER: "#a8a29e",
  UNKNOWN: "#525252",
};
