import type { DirectoryAgent } from "./types";

export const SEED_AGENTS: readonly DirectoryAgent[] = [
  // ─── Keepers ────────────────────────────────────────────────────────────
  {
    address: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
    chainId: "ethereum",
    name: "ERC-4337 EntryPoint",
    agentType: "KEEPER",
    score: 92,
    recommendation: "SAFE",
    behavioralNarrative: "Core account abstraction infrastructure. Processes UserOps with extreme regularity — 14k+ daily transactions, near-zero downtime since deployment.",
    financialSummary: { totalGasSpentETH: "284.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.98 },
    protocolsUsed: ["ERC-4337", "Bundler Network"],
    funFact: "Processes more transactions than most L2s combined.",
    anomalies: [],
    txCount: 892341,
    lastActive: Date.now() - 12000,
    source: "seed",
  },
  {
    address: "0x02777053d6764996e594c3E88AF1D58D5363a2e6",
    chainId: "ethereum",
    name: "Chainlink Automation Registry v2.1",
    agentType: "KEEPER",
    score: 95,
    recommendation: "SAFE",
    behavioralNarrative: "Decentralized automation network executing upkeep tasks. Highly consistent timing patterns with multi-node redundancy.",
    financialSummary: { totalGasSpentETH: "1204.3", netFlowETH: "+12.8" },
    operationalPattern: { peakHoursUTC: [10, 11, 14, 15], consistencyScore: 0.97 },
    protocolsUsed: ["Chainlink Automation", "Chainlink Keepers"],
    funFact: "Has never missed a critical upkeep since v2.1 launch.",
    anomalies: [],
    txCount: 1456782,
    lastActive: Date.now() - 8000,
    source: "seed",
  },
  {
    address: "0x29b6603D17B9D8f021EcB8845B6FD06E1Adf89DE",
    chainId: "ethereum",
    name: "Gelato Automate",
    agentType: "KEEPER",
    score: 89,
    recommendation: "SAFE",
    behavioralNarrative: "Web3 automation relay executing scheduled tasks and conditional transactions. Operates across multiple chains with gasless relay support.",
    financialSummary: { totalGasSpentETH: "421.6", netFlowETH: "+3.2" },
    operationalPattern: { peakHoursUTC: [12, 13, 16, 17], consistencyScore: 0.94 },
    protocolsUsed: ["Gelato Network", "Gelato Relay"],
    funFact: "Processes automation tasks for 400+ DeFi protocols.",
    anomalies: [],
    txCount: 672109,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0x0048a99770E1fF60c40aDa7863b2E30E1F23538b",
    chainId: "base",
    name: "Keep3r V2 Job Registry",
    agentType: "KEEPER",
    score: 82,
    recommendation: "SAFE",
    behavioralNarrative: "Keeper network job coordination. Moderate activity with consistent execution patterns across registered jobs.",
    financialSummary: { totalGasSpentETH: "18.4", netFlowETH: "+0.9" },
    operationalPattern: { peakHoursUTC: [8, 9, 20, 21], consistencyScore: 0.88 },
    protocolsUsed: ["Keep3r V2"],
    funFact: "Andre Cronje's original keeper network — still running.",
    anomalies: [],
    txCount: 34521,
    lastActive: Date.now() - 45000,
    source: "seed",
  },
  {
    address: "0x271682DEB8C4E0901D1a1550aD2e64D568E69909",
    chainId: "ethereum",
    name: "Chainlink VRF Coordinator V2",
    agentType: "KEEPER",
    score: 94,
    recommendation: "SAFE",
    behavioralNarrative: "Verifiable random function coordinator fulfilling randomness requests for NFT mints, gaming, and lotteries. Each fulfillment includes a cryptographic proof.",
    financialSummary: { totalGasSpentETH: "678.9", netFlowETH: "+8.4" },
    operationalPattern: { peakHoursUTC: [14, 15, 19, 20], consistencyScore: 0.96 },
    protocolsUsed: ["Chainlink VRF", "Chainlink"],
    funFact: "Generated randomness for over 10M NFT mints without a single dispute.",
    anomalies: [],
    txCount: 987234,
    lastActive: Date.now() - 5000,
    source: "seed",
  },
  {
    address: "0x5A023A4De9da7a20c1bE0CBA3e9643D1EcF02d49",
    chainId: "ethereum",
    name: "MakerDAO Keeper (Bark)",
    agentType: "KEEPER",
    score: 87,
    recommendation: "SAFE",
    behavioralNarrative: "Triggers Maker vault liquidation auctions when collateral ratios drop below threshold. Critical protocol safety mechanism.",
    financialSummary: { totalGasSpentETH: "45.3", netFlowETH: "+2.1" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.91 },
    protocolsUsed: ["MakerDAO", "Maker Liquidations"],
    funFact: "Barks at undercollateralized vaults — literally named after a dog's alert.",
    anomalies: [],
    txCount: 28934,
    lastActive: Date.now() - 75000,
    source: "seed",
  },
  {
    address: "0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41",
    chainId: "ethereum",
    name: "ENS Public Resolver Keeper",
    agentType: "KEEPER",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "Handles ENS name resolution updates and record maintenance. Executes with metronomic regularity as names are registered and renewed.",
    financialSummary: { totalGasSpentETH: "112.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.93 },
    protocolsUsed: ["ENS", "ENS Resolver"],
    funFact: "Resolved over 2M .eth names — the phone book of Web3.",
    anomalies: [],
    txCount: 456789,
    lastActive: Date.now() - 20000,
    source: "seed",
  },
  {
    address: "0xB63e54feA30d5af5dC15c0c3F38e2AB29Abe39C0",
    chainId: "arbitrum",
    name: "Gelato Relay Arbitrum",
    agentType: "KEEPER",
    score: 85,
    recommendation: "SAFE",
    behavioralNarrative: "Gelato gasless relay on Arbitrum executing meta-transactions and automated tasks. Higher throughput than mainnet due to lower gas costs.",
    financialSummary: { totalGasSpentETH: "8.7", netFlowETH: "+0.4" },
    operationalPattern: { peakHoursUTC: [13, 14, 15, 16], consistencyScore: 0.90 },
    protocolsUsed: ["Gelato Network", "Arbitrum"],
    funFact: "Executes 5x more tasks per ETH spent than its mainnet counterpart.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 11000,
    source: "seed",
  },
  {
    address: "0x7b1237068Fe740F07e35B5E24AcEe37eCDc5F862",
    chainId: "optimism",
    name: "Chainlink Automation Optimism",
    agentType: "KEEPER",
    score: 88,
    recommendation: "SAFE",
    behavioralNarrative: "Chainlink Automation on Optimism processing conditional upkeeps. Benefits from OP Stack's low fees for high-frequency automation.",
    financialSummary: { totalGasSpentETH: "4.2", netFlowETH: "+0.3" },
    operationalPattern: { peakHoursUTC: [10, 11, 15, 16], consistencyScore: 0.92 },
    protocolsUsed: ["Chainlink Automation", "Optimism"],
    funFact: "Costs 98% less per upkeep than the same task on Ethereum mainnet.",
    anomalies: [],
    txCount: 189012,
    lastActive: Date.now() - 13000,
    source: "seed",
  },
  {
    address: "0x6593c7De001fC8afB6068a2313C4e965c3fca978",
    chainId: "polygon",
    name: "Chainlink Keeper Registry Polygon",
    agentType: "KEEPER",
    score: 86,
    recommendation: "SAFE",
    behavioralNarrative: "Chainlink Keeper infrastructure on Polygon handling time-based and conditional upkeeps for DeFi protocols on the network.",
    financialSummary: { totalGasSpentETH: "3.1", netFlowETH: "+0.2" },
    operationalPattern: { peakHoursUTC: [9, 10, 14, 15], consistencyScore: 0.89 },
    protocolsUsed: ["Chainlink Keepers", "Polygon"],
    funFact: "Runs on MATIC but reports to Ethereum for cross-chain verification.",
    anomalies: [],
    txCount: 145678,
    lastActive: Date.now() - 25000,
    source: "seed",
  },
  {
    address: "0xE0c5ceA4D3869F156717C66E188Ae81C0b4Bd89E",
    chainId: "gnosis",
    name: "Gnosis Chain Keeper Bot",
    agentType: "KEEPER",
    score: 47,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Unverified keeper bot on Gnosis Chain with erratic execution patterns. Frequently submits duplicate transactions and has been observed extracting value from keeper tasks.",
    financialSummary: { totalGasSpentETH: "0.8", netFlowETH: "+2.3" },
    operationalPattern: { peakHoursUTC: [3, 4, 5], consistencyScore: 0.35 },
    protocolsUsed: ["Gnosis Chain", "Agave"],
    funFact: "Submits 3x more transactions than needed — wasting gas on duplicate attempts.",
    anomalies: ["Duplicate transaction submissions", "Value extraction from keeper tasks", "Unverified contract"],
    txCount: 67890,
    lastActive: Date.now() - 60000,
    source: "seed",
  },
  {
    address: "0x0000000000007F150Bd6f54c40A34d7C3d5e9f56",
    chainId: "ethereum",
    name: "ERC-4337 EntryPoint v0.7",
    agentType: "KEEPER",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "Next-gen account abstraction entry point with improved gas estimation and paymaster support. Growing rapidly as AA wallets migrate.",
    financialSummary: { totalGasSpentETH: "56.3", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.95 },
    protocolsUsed: ["ERC-4337 v0.7", "Bundler Network"],
    funFact: "Reduces bundler gas overhead by 20% compared to v0.6.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 6000,
    source: "seed",
  },

  // ─── Oracles ────────────────────────────────────────────────────────────
  {
    address: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419",
    chainId: "ethereum",
    name: "Chainlink ETH/USD Price Feed",
    agentType: "ORACLE",
    score: 97,
    recommendation: "SAFE",
    behavioralNarrative: "Primary ETH/USD price oracle. Updates with heartbeat precision — deviation threshold triggers within seconds. Backbone of DeFi pricing.",
    financialSummary: { totalGasSpentETH: "892.1", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.99 },
    protocolsUsed: ["Chainlink", "Chainlink Price Feeds"],
    funFact: "Secures over $20B in DeFi TVL with a single price feed.",
    anomalies: [],
    txCount: 2891034,
    lastActive: Date.now() - 3000,
    source: "seed",
  },
  {
    address: "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C",
    chainId: "ethereum",
    name: "Pyth Network Price Pusher",
    agentType: "ORACLE",
    score: 88,
    recommendation: "SAFE",
    behavioralNarrative: "Pull-based oracle pushing Pyth price updates on-demand. Bursty activity aligned with market volatility spikes.",
    financialSummary: { totalGasSpentETH: "156.3", netFlowETH: "-2.1" },
    operationalPattern: { peakHoursUTC: [13, 14, 15, 20], consistencyScore: 0.85 },
    protocolsUsed: ["Pyth Network", "Wormhole"],
    funFact: "Activity correlates 0.94 with VIX — busier when markets panic.",
    anomalies: [],
    txCount: 489201,
    lastActive: Date.now() - 22000,
    source: "seed",
  },
  {
    address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
    chainId: "ethereum",
    name: "Lido wstETH Oracle Reporter",
    agentType: "ORACLE",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "Reports stETH exchange rate updates from Lido oracle committee. Predictable daily cadence with multi-sig oracle consensus.",
    financialSummary: { totalGasSpentETH: "67.2", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [12, 13], consistencyScore: 0.96 },
    protocolsUsed: ["Lido", "Lido Oracle"],
    funFact: "Updates exactly once per day — the most punctual agent in DeFi.",
    anomalies: [],
    txCount: 12890,
    lastActive: Date.now() - 60000,
    source: "seed",
  },
  {
    address: "0x47Fb2585D2C56Fe188D0E6ec628a38b74fCeeeDf",
    chainId: "ethereum",
    name: "UMA Optimistic Oracle",
    agentType: "ORACLE",
    score: 84,
    recommendation: "SAFE",
    behavioralNarrative: "Dispute-based oracle resolving arbitrary data requests. Activity spikes during governance votes and insurance claim periods.",
    financialSummary: { totalGasSpentETH: "34.8", netFlowETH: "+1.2" },
    operationalPattern: { peakHoursUTC: [15, 16, 17], consistencyScore: 0.79 },
    protocolsUsed: ["UMA Protocol", "Polymarket"],
    funFact: "Powered every Polymarket election prediction in 2024.",
    anomalies: [],
    txCount: 89102,
    lastActive: Date.now() - 180000,
    source: "seed",
  },
  {
    address: "0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c",
    chainId: "ethereum",
    name: "Chainlink BTC/USD Price Feed",
    agentType: "ORACLE",
    score: 96,
    recommendation: "SAFE",
    behavioralNarrative: "Primary BTC/USD price oracle securing billions in lending collateral. Heartbeat updates every 3600s with 0.5% deviation threshold.",
    financialSummary: { totalGasSpentETH: "745.3", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.99 },
    protocolsUsed: ["Chainlink", "Chainlink Price Feeds"],
    funFact: "The most queried price feed in all of DeFi — called 100M+ times.",
    anomalies: [],
    txCount: 2456789,
    lastActive: Date.now() - 4000,
    source: "seed",
  },
  {
    address: "0xb56c2F0B653B2e0b10C9b928C8580Ac5Df02C7C7",
    chainId: "ethereum",
    name: "Tellor Oracle Reporter",
    agentType: "ORACLE",
    score: 67,
    recommendation: "CAUTION",
    behavioralNarrative: "Decentralized oracle with staked reporters submitting data on-chain. Dispute mechanism allows anyone to challenge bad data with a bond.",
    financialSummary: { totalGasSpentETH: "23.4", netFlowETH: "+1.8" },
    operationalPattern: { peakHoursUTC: [14, 15, 16], consistencyScore: 0.74 },
    protocolsUsed: ["Tellor", "Tellor Dispute"],
    funFact: "Any reporter can be slashed if their data is proven wrong within 12 hours.",
    anomalies: ["Reporter dispute rate higher than average — 3 successful challenges in 90 days"],
    txCount: 45678,
    lastActive: Date.now() - 120000,
    source: "seed",
  },
  {
    address: "0x0AdDd25a91563696D8567Df78D5A01C9a991F9B8",
    chainId: "ethereum",
    name: "Chronicle Protocol Oracle",
    agentType: "ORACLE",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "Formerly MakerDAO's internal oracle infrastructure, now an independent protocol. Schnorr signature aggregation for gas-efficient multi-source price updates.",
    financialSummary: { totalGasSpentETH: "89.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.95 },
    protocolsUsed: ["Chronicle", "MakerDAO"],
    funFact: "Uses Schnorr signatures to aggregate 13 oracle reports into one tx.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0x3d5Bc3c8d13DcB8bF317092d84783c2697AE9258",
    chainId: "ethereum",
    name: "API3 dAPI Server",
    agentType: "ORACLE",
    score: 83,
    recommendation: "SAFE",
    behavioralNarrative: "First-party oracle where API providers run their own oracle nodes. No middleman layer — data goes directly from source to chain.",
    financialSummary: { totalGasSpentETH: "34.1", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.82 },
    protocolsUsed: ["API3", "Airnode"],
    funFact: "API providers operate their own nodes — cutting out the oracle middleman.",
    anomalies: [],
    txCount: 78901,
    lastActive: Date.now() - 45000,
    source: "seed",
  },
  {
    address: "0x65c816077C29b557BEE980ae3cC2dCE01028DE44",
    chainId: "arbitrum",
    name: "RedStone Price Feed Arbitrum",
    agentType: "ORACLE",
    score: 61,
    recommendation: "CAUTION",
    behavioralNarrative: "Modular oracle delivering price data via EVM calldata instead of on-chain storage. Novel approach but limited track record compared to established oracles.",
    financialSummary: { totalGasSpentETH: "2.3", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.80 },
    protocolsUsed: ["RedStone", "Arbitrum"],
    funFact: "Passes price data in calldata — never stores it on-chain until consumed.",
    anomalies: ["Calldata-only oracle — data not independently verifiable on-chain"],
    txCount: 123456,
    lastActive: Date.now() - 30000,
    source: "seed",
  },
  {
    address: "0xFdB631F5EE196F0ed6FAa767959853A9F217697D",
    chainId: "optimism",
    name: "Chainlink LINK/USD Optimism",
    agentType: "ORACLE",
    score: 93,
    recommendation: "SAFE",
    behavioralNarrative: "Chainlink price feed on Optimism for LINK/USD. L2 deployment allows sub-cent update costs while maintaining mainnet-grade security.",
    financialSummary: { totalGasSpentETH: "1.8", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.97 },
    protocolsUsed: ["Chainlink", "Optimism"],
    funFact: "Each price update costs less than a penny on Optimism.",
    anomalies: [],
    txCount: 567890,
    lastActive: Date.now() - 8000,
    source: "seed",
  },
  {
    address: "0xA2aa501b19aff244D90cc15a4Cf739D2725B5729",
    chainId: "gnosis",
    name: "Gnosis Chain Chainlink Feed",
    agentType: "ORACLE",
    score: 80,
    recommendation: "SAFE",
    behavioralNarrative: "Chainlink price oracle deployment on Gnosis Chain serving xDAI-native DeFi protocols. Lower update frequency tuned for the chain's transaction volume.",
    financialSummary: { totalGasSpentETH: "0.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 12], consistencyScore: 0.84 },
    protocolsUsed: ["Chainlink", "Gnosis Chain"],
    funFact: "Updates cost fractions of a cent thanks to Gnosis Chain's xDAI gas.",
    anomalies: [],
    txCount: 89012,
    lastActive: Date.now() - 90000,
    source: "seed",
  },

  // ─── Bridge Relayers ────────────────────────────────────────────────────
  {
    address: "0x5c7BCd6E7De5423a257D81B442095A1a6ced35C5",
    chainId: "ethereum",
    name: "Across Protocol Relayer",
    agentType: "BRIDGE_RELAYER",
    score: 86,
    recommendation: "SAFE",
    behavioralNarrative: "Optimistic bridge relayer fulfilling cross-chain intents. High-value transfers with rapid finality — typically 2-10 seconds for most routes.",
    financialSummary: { totalGasSpentETH: "312.4", netFlowETH: "+89.3" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.91 },
    protocolsUsed: ["Across Protocol", "UMA"],
    funFact: "Relays more volume per dollar of gas than any other bridge.",
    anomalies: [],
    txCount: 234891,
    lastActive: Date.now() - 5000,
    source: "seed",
  },
  {
    address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
    chainId: "polygon",
    name: "Stargate Finance Relayer",
    agentType: "BRIDGE_RELAYER",
    score: 83,
    recommendation: "SAFE",
    behavioralNarrative: "LayerZero-based bridge relayer executing cross-chain swaps via unified liquidity pools. Consistent volume across 8+ chains.",
    financialSummary: { totalGasSpentETH: "78.9", netFlowETH: "+24.6" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 22], consistencyScore: 0.87 },
    protocolsUsed: ["Stargate", "LayerZero"],
    funFact: "Moves USDC between chains faster than most CEX withdrawals.",
    anomalies: [],
    txCount: 156234,
    lastActive: Date.now() - 30000,
    source: "seed",
  },
  {
    address: "0x3154Cf16ccdb4C6d922629664174b904d80F2C35",
    chainId: "base",
    name: "Base Bridge Operator",
    agentType: "BRIDGE_RELAYER",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "Official Base L1→L2 message relayer. Processes deposits and withdrawals with Optimism Bedrock finality guarantees.",
    financialSummary: { totalGasSpentETH: "523.1", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.95 },
    protocolsUsed: ["OP Stack", "Base Bridge"],
    funFact: "Processes $2M+ in daily bridge volume for Coinbase users.",
    anomalies: [],
    txCount: 891023,
    lastActive: Date.now() - 7000,
    source: "seed",
  },
  {
    address: "0xaBEA9132b05A70803a4E85094fD0e1800777fBEF",
    chainId: "arbitrum",
    name: "Hop Protocol Bonder",
    agentType: "BRIDGE_RELAYER",
    score: 80,
    recommendation: "SAFE",
    behavioralNarrative: "Liquidity bonder providing instant cross-chain transfers by fronting assets. Moderate risk tolerance with bonded collateral backing.",
    financialSummary: { totalGasSpentETH: "145.2", netFlowETH: "+31.7" },
    operationalPattern: { peakHoursUTC: [13, 14, 19, 20], consistencyScore: 0.83 },
    protocolsUsed: ["Hop Protocol"],
    funFact: "One of the earliest bridge bonders — active since Arbitrum launch.",
    anomalies: [],
    txCount: 67234,
    lastActive: Date.now() - 120000,
    source: "seed",
  },
  {
    address: "0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B",
    chainId: "ethereum",
    name: "Wormhole Core Bridge",
    agentType: "BRIDGE_RELAYER",
    score: 62,
    recommendation: "CAUTION",
    behavioralNarrative: "Core Wormhole bridge contract processing cross-chain messages via Guardian network. High throughput but historically targeted by exploits.",
    financialSummary: { totalGasSpentETH: "1234.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.88 },
    protocolsUsed: ["Wormhole", "Guardian Network"],
    funFact: "Survived a $320M exploit and rebuilt its Guardian set from scratch.",
    anomalies: ["Historical exploit: $320M bridge hack in Feb 2022"],
    txCount: 1234567,
    lastActive: Date.now() - 3000,
    source: "seed",
  },
  {
    address: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F",
    chainId: "ethereum",
    name: "Synapse Protocol Router",
    agentType: "BRIDGE_RELAYER",
    score: 77,
    recommendation: "SAFE",
    behavioralNarrative: "Multi-chain bridge router using optimistic verification with Synapse's native nUSD/nETH liquidity. Supports 15+ chains.",
    financialSummary: { totalGasSpentETH: "189.4", netFlowETH: "+45.2" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 21], consistencyScore: 0.84 },
    protocolsUsed: ["Synapse Protocol", "Synapse Bridge"],
    funFact: "Routes through its own stablecoin (nUSD) for zero-slippage transfers.",
    anomalies: [],
    txCount: 345678,
    lastActive: Date.now() - 18000,
    source: "seed",
  },
  {
    address: "0x5427FEFA711Eff984124bFBB1AB6fbf5E3DA1820",
    chainId: "ethereum",
    name: "cBridge (Celer Network)",
    agentType: "BRIDGE_RELAYER",
    score: 74,
    recommendation: "CAUTION",
    behavioralNarrative: "Celer's liquidity network bridge with SGN (State Guardian Network) validation. Competitive fees but centralized guardian set raises trust concerns.",
    financialSummary: { totalGasSpentETH: "234.1", netFlowETH: "+67.8" },
    operationalPattern: { peakHoursUTC: [10, 14, 20, 21], consistencyScore: 0.81 },
    protocolsUsed: ["Celer Network", "cBridge"],
    funFact: "Uses a State Guardian Network of 21 validators — more than most L1s.",
    anomalies: ["Centralized guardian set: 21 validators control message validation"],
    txCount: 234567,
    lastActive: Date.now() - 25000,
    source: "seed",
  },
  {
    address: "0xc30141B657f4216252dc59Af2e7CdB9D8792e1B0",
    chainId: "ethereum",
    name: "Socket Gateway",
    agentType: "BRIDGE_RELAYER",
    score: 82,
    recommendation: "SAFE",
    behavioralNarrative: "Meta-bridge aggregator routing transfers through the optimal bridge for each route. Compares Across, Hop, Stargate, and others in real-time.",
    financialSummary: { totalGasSpentETH: "156.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.86 },
    protocolsUsed: ["Socket", "Bungee"],
    funFact: "Compares 10+ bridges per transfer to find the cheapest route.",
    anomalies: [],
    txCount: 567890,
    lastActive: Date.now() - 9000,
    source: "seed",
  },
  {
    address: "0xeE56e2B3D491590B5b31738cC34d5232F378a8D5",
    chainId: "optimism",
    name: "Connext Bridge Optimism",
    agentType: "BRIDGE_RELAYER",
    score: 58,
    recommendation: "CAUTION",
    behavioralNarrative: "Connext's NXTP bridge on Optimism using a router network for fast cross-chain liquidity. Routers front capital and get reimbursed after settlement.",
    financialSummary: { totalGasSpentETH: "12.3", netFlowETH: "+3.4" },
    operationalPattern: { peakHoursUTC: [14, 15, 20, 21], consistencyScore: 0.78 },
    protocolsUsed: ["Connext", "Optimism"],
    funFact: "Routers earn yield by fronting bridge capital — a DeFi primitive inside a bridge.",
    anomalies: ["Router set is permissioned — limited decentralization"],
    txCount: 89012,
    lastActive: Date.now() - 45000,
    source: "seed",
  },
  {
    address: "0xf92cD566Ea4864356C5491c177A430C222d7e678",
    chainId: "gnosis",
    name: "Gnosis Omnibridge",
    agentType: "BRIDGE_RELAYER",
    score: 64,
    recommendation: "CAUTION",
    behavioralNarrative: "Native Gnosis Chain bridge for ERC-20 token transfers between Ethereum and Gnosis. Uses AMB (Arbitrary Message Bridge) validators.",
    financialSummary: { totalGasSpentETH: "2.1", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15], consistencyScore: 0.82 },
    protocolsUsed: ["Gnosis Bridge", "AMB"],
    funFact: "One of the oldest production bridges — running since 2020.",
    anomalies: ["Legacy bridge architecture — no fraud proofs or validity proofs"],
    txCount: 234567,
    lastActive: Date.now() - 60000,
    source: "seed",
  },
  {
    address: "0x4Dbd4fc535Ac27206064B68FfCf827b0A60BAB3f",
    chainId: "ethereum",
    name: "Arbitrum Delayed Inbox",
    agentType: "BRIDGE_RELAYER",
    score: 93,
    recommendation: "SAFE",
    behavioralNarrative: "Official Arbitrum L1→L2 message relay processing ETH and token deposits into Arbitrum One. Core rollup infrastructure operated by Offchain Labs.",
    financialSummary: { totalGasSpentETH: "2345.6", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.96 },
    protocolsUsed: ["Arbitrum", "Nitro"],
    funFact: "Processes more deposit volume than all independent bridges combined.",
    anomalies: [],
    txCount: 2345678,
    lastActive: Date.now() - 2000,
    source: "seed",
  },

  // ─── Liquidators ────────────────────────────────────────────────────────
  {
    address: "0x80226Fc0Ee2b096224EeAc085Bb9a8cba1146f7D",
    chainId: "ethereum",
    name: "Aave V3 Liquidation Bot",
    agentType: "LIQUIDATOR",
    score: 74,
    recommendation: "CAUTION",
    behavioralNarrative: "Aggressive liquidation bot targeting undercollateralized Aave V3 positions. Spikes during market downturns — 40x normal volume during crash events.",
    financialSummary: { totalGasSpentETH: "89.4", netFlowETH: "+234.8" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.62 },
    protocolsUsed: ["Aave V3", "Flashbots"],
    funFact: "Earned 234 ETH profit during the March 2024 liquidation cascade.",
    anomalies: ["Burst activity: 400+ txns in 10 minutes during market stress"],
    txCount: 45123,
    lastActive: Date.now() - 90000,
    source: "seed",
  },
  {
    address: "0xc3D688B66703497DAA19211EEdff47f25384cdc3",
    chainId: "ethereum",
    name: "Compound V3 Absorber",
    agentType: "LIQUIDATOR",
    score: 78,
    recommendation: "CAUTION",
    behavioralNarrative: "Compound III absorber bot converting underwater positions. Methodical approach — queues positions by health factor and liquidates in batches.",
    financialSummary: { totalGasSpentETH: "34.2", netFlowETH: "+67.1" },
    operationalPattern: { peakHoursUTC: [8, 9, 14, 15], consistencyScore: 0.71 },
    protocolsUsed: ["Compound V3"],
    funFact: "Batches liquidations to save 30% on gas vs individual calls.",
    anomalies: [],
    txCount: 23891,
    lastActive: Date.now() - 200000,
    source: "seed",
  },
  {
    address: "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e",
    chainId: "ethereum",
    name: "Aave V3 Pool Liquidator",
    agentType: "LIQUIDATOR",
    score: 71,
    recommendation: "CAUTION",
    behavioralNarrative: "Secondary Aave liquidator operating with Flashbots bundles. Lower latency competitor — occasionally front-runs primary liquidators via MEV.",
    financialSummary: { totalGasSpentETH: "56.8", netFlowETH: "+112.4" },
    operationalPattern: { peakHoursUTC: [2, 3, 14, 15], consistencyScore: 0.58 },
    protocolsUsed: ["Aave V3", "Flashbots", "MEV-Boost"],
    funFact: "Uses MEV-Boost to guarantee inclusion — never gets reverted.",
    anomalies: ["MEV bundle usage for liquidation front-running"],
    txCount: 31209,
    lastActive: Date.now() - 150000,
    source: "seed",
  },
  {
    address: "0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb",
    chainId: "ethereum",
    name: "Morpho Blue Liquidator",
    agentType: "LIQUIDATOR",
    score: 76,
    recommendation: "CAUTION",
    behavioralNarrative: "Liquidation bot for Morpho Blue isolated lending markets. Monitors hundreds of isolated markets simultaneously for underwater positions.",
    financialSummary: { totalGasSpentETH: "23.4", netFlowETH: "+45.6" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.65 },
    protocolsUsed: ["Morpho Blue", "Flashbots"],
    funFact: "Monitors 200+ isolated lending markets — each with unique collateral ratios.",
    anomalies: ["Burst activity during ETH price drops > 5%"],
    txCount: 12345,
    lastActive: Date.now() - 110000,
    source: "seed",
  },
  {
    address: "0x135896DE8421be2ec868E0b811006171D9df802A",
    chainId: "ethereum",
    name: "MakerDAO Dog (Liquidation Engine)",
    agentType: "LIQUIDATOR",
    score: 85,
    recommendation: "SAFE",
    behavioralNarrative: "MakerDAO's Liquidation 2.0 engine using Dutch auctions. Processes vault liquidations with decreasing price auctions for fair collateral recovery.",
    financialSummary: { totalGasSpentETH: "78.9", netFlowETH: "+156.3" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.73 },
    protocolsUsed: ["MakerDAO", "Maker Liquidations 2.0"],
    funFact: "Dutch auctions start at 2x market price and decrease — penalizing slow bidders.",
    anomalies: [],
    txCount: 34567,
    lastActive: Date.now() - 95000,
    source: "seed",
  },
  {
    address: "0x794a61358D6845594F94dc1DB02A252b5b4814aD",
    chainId: "arbitrum",
    name: "Aave V3 Liquidator Arbitrum",
    agentType: "LIQUIDATOR",
    score: 72,
    recommendation: "CAUTION",
    behavioralNarrative: "Aave V3 liquidation bot on Arbitrum. Lower gas costs allow liquidating smaller positions that would be unprofitable on mainnet.",
    financialSummary: { totalGasSpentETH: "4.5", netFlowETH: "+23.1" },
    operationalPattern: { peakHoursUTC: [2, 3, 14, 15], consistencyScore: 0.60 },
    protocolsUsed: ["Aave V3", "Arbitrum"],
    funFact: "Profitably liquidates positions as small as $50 thanks to L2 gas savings.",
    anomalies: ["High-frequency liquidation bursts during volatile periods"],
    txCount: 56789,
    lastActive: Date.now() - 85000,
    source: "seed",
  },
  {
    address: "0xe7870231992Ab4b1A01814FA0A599115FE94203f",
    chainId: "ethereum",
    name: "dYdX Liquidation Engine",
    agentType: "LIQUIDATOR",
    score: 81,
    recommendation: "SAFE",
    behavioralNarrative: "Perpetual futures liquidation engine processing underwater margin positions. Handles cascading liquidations during leverage unwinds.",
    financialSummary: { totalGasSpentETH: "156.7", netFlowETH: "+289.4" },
    operationalPattern: { peakHoursUTC: [2, 3, 10, 14], consistencyScore: 0.68 },
    protocolsUsed: ["dYdX", "StarkEx"],
    funFact: "Processed $2B in liquidations during the 2024 crypto crash in 48 hours.",
    anomalies: [],
    txCount: 78901,
    lastActive: Date.now() - 130000,
    source: "seed",
  },
  {
    address: "0x3520d5a913427E6F0D6A83E07ccD4A4da316e4d3",
    chainId: "polygon",
    name: "Aave V3 Liquidator Polygon",
    agentType: "LIQUIDATOR",
    score: 69,
    recommendation: "CAUTION",
    behavioralNarrative: "Polygon-based Aave V3 liquidator. Extremely high throughput due to sub-cent gas costs. More aggressive than mainnet counterparts.",
    financialSummary: { totalGasSpentETH: "1.2", netFlowETH: "+12.3" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.55 },
    protocolsUsed: ["Aave V3", "Polygon"],
    funFact: "Executes 10x more liquidation attempts than mainnet bots — most are tiny.",
    anomalies: ["Very high attempt frequency — many small liquidations"],
    txCount: 234567,
    lastActive: Date.now() - 70000,
    source: "seed",
  },
  {
    address: "0xA238Dd80C259a72e81d7e4664a9801593F98d1c5",
    chainId: "ethereum",
    name: "Euler Finance Liquidator",
    agentType: "LIQUIDATOR",
    score: 42,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Euler liquidation bot with suspicious activity patterns. Unusually timed transactions suggest possible oracle manipulation for forced liquidations.",
    financialSummary: { totalGasSpentETH: "67.8", netFlowETH: "+345.6" },
    operationalPattern: { peakHoursUTC: [3, 4, 5], consistencyScore: 0.35 },
    protocolsUsed: ["Euler Finance", "Flashbots"],
    funFact: "Operates exclusively during Asian market hours when liquidity is thinnest.",
    anomalies: ["Suspicious timing correlation with oracle price deviations", "Possible oracle manipulation"],
    txCount: 12345,
    lastActive: Date.now() - 200000,
    source: "seed",
  },
  {
    address: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5",
    chainId: "ethereum",
    name: "Aave V2 Legacy Liquidator",
    agentType: "LIQUIDATOR",
    score: 77,
    recommendation: "SAFE",
    behavioralNarrative: "Legacy Aave V2 liquidation bot still operating on remaining V2 positions. Declining activity as users migrate to V3.",
    financialSummary: { totalGasSpentETH: "234.5", netFlowETH: "+456.7" },
    operationalPattern: { peakHoursUTC: [2, 3, 14, 15], consistencyScore: 0.70 },
    protocolsUsed: ["Aave V2"],
    funFact: "Still profitable on V2 because fewer bots compete for the remaining positions.",
    anomalies: [],
    txCount: 89012,
    lastActive: Date.now() - 250000,
    source: "seed",
  },
  {
    address: "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",
    chainId: "base",
    name: "Compound Fork Liquidator (Base)",
    agentType: "LIQUIDATOR",
    score: 68,
    recommendation: "CAUTION",
    behavioralNarrative: "Liquidation bot targeting Compound forks on Base. Monitors multiple fork deployments simultaneously for underwater positions.",
    financialSummary: { totalGasSpentETH: "0.8", netFlowETH: "+4.5" },
    operationalPattern: { peakHoursUTC: [2, 3, 14, 15], consistencyScore: 0.57 },
    protocolsUsed: ["Moonwell", "Seamless Protocol"],
    funFact: "Monitors 4 different Compound forks on Base from a single bot.",
    anomalies: ["Targets multiple fork protocols — potential for cross-protocol exploits"],
    txCount: 23456,
    lastActive: Date.now() - 55000,
    source: "seed",
  },
  {
    address: "0x60744434d6339a6B27d73d9Eda62b6F66a0a04FA",
    chainId: "optimism",
    name: "Sonne Finance Liquidator",
    agentType: "LIQUIDATOR",
    score: 73,
    recommendation: "CAUTION",
    behavioralNarrative: "Lending protocol liquidation bot on Optimism. Specializes in Sonne Finance positions with moderate activity and reasonable execution timing.",
    financialSummary: { totalGasSpentETH: "1.5", netFlowETH: "+8.9" },
    operationalPattern: { peakHoursUTC: [2, 8, 14], consistencyScore: 0.63 },
    protocolsUsed: ["Sonne Finance", "Optimism"],
    funFact: "One of the few liquidators that exclusively operates on a single L2.",
    anomalies: ["Occasional unusually large gas bids during competitive liquidations"],
    txCount: 15678,
    lastActive: Date.now() - 100000,
    source: "seed",
  },

  // ─── MEV Bots ───────────────────────────────────────────────────────────
  {
    address: "0x56178a0d5F301bAf6CF3e1Cd53d9863437345Bf9",
    chainId: "ethereum",
    name: "MEV Bot: Sandwich Hunter",
    agentType: "MEV_BOT",
    score: 31,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Aggressive sandwich attacker targeting large DEX swaps. Front-runs and back-runs victim transactions in atomic bundles. Extracted 890 ETH in 90 days.",
    financialSummary: { totalGasSpentETH: "234.5", netFlowETH: "+890.2" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.45 },
    protocolsUsed: ["Uniswap V2", "Uniswap V3", "Flashbots"],
    funFact: "This bot has sandwiched more retail traders than any NYC deli.",
    anomalies: ["Sandwich attack pattern detected", "Targets swaps > 10 ETH"],
    txCount: 234891,
    lastActive: Date.now() - 4000,
    source: "seed",
  },
  {
    address: "0x00000000000747D525E898A17AE89C6800FF3Cf2",
    chainId: "ethereum",
    name: "MEV Bot: JIT Liquidity",
    agentType: "MEV_BOT",
    score: 52,
    recommendation: "CAUTION",
    behavioralNarrative: "Just-in-time liquidity provider. Adds concentrated liquidity milliseconds before large swaps, captures fees, removes immediately after.",
    financialSummary: { totalGasSpentETH: "167.3", netFlowETH: "+412.8" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.39 },
    protocolsUsed: ["Uniswap V3", "Flashbots"],
    funFact: "Provides better execution for traders while extracting MEV — a rare win-win.",
    anomalies: ["JIT liquidity manipulation detected"],
    txCount: 178923,
    lastActive: Date.now() - 6000,
    source: "seed",
  },
  {
    address: "0xA69babEF1cA67A37Ffaf7a485DfFF3382056e78C",
    chainId: "ethereum",
    name: "MEV Bot: Backrunner",
    agentType: "MEV_BOT",
    score: 44,
    recommendation: "CAUTION",
    behavioralNarrative: "Opportunistic backrunner exploiting arbitrage created by large swaps. Less harmful than sandwich bots but still extracts value from orderflow.",
    financialSummary: { totalGasSpentETH: "89.1", netFlowETH: "+201.4" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.52 },
    protocolsUsed: ["Uniswap V2", "SushiSwap", "Flashbots"],
    funFact: "Failed 34% of its transactions — the cost of doing MEV.",
    anomalies: ["High revert rate: 34%"],
    txCount: 145672,
    lastActive: Date.now() - 18000,
    source: "seed",
  },
  {
    address: "0xae2Fc483527B8EF99EB5D9B44875F005ba1FaE13",
    chainId: "ethereum",
    name: "jaredfromsubway.eth",
    agentType: "MEV_BOT",
    score: 25,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Notorious sandwich bot that extracted millions from retail traders. One of the most profitable and aggressive MEV operators in Ethereum history.",
    financialSummary: { totalGasSpentETH: "4567.8", netFlowETH: "+8901.2" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17, 20, 21], consistencyScore: 0.42 },
    protocolsUsed: ["Uniswap V2", "Uniswap V3", "Flashbots", "SushiSwap"],
    funFact: "Spent more on gas in 2023 than most DeFi protocols earned in revenue.",
    anomalies: ["Prolific sandwich attacker", "Extracted 8900+ ETH from retail", "Top gas spender on Ethereum"],
    txCount: 3456789,
    lastActive: Date.now() - 2000,
    source: "seed",
  },
  {
    address: "0x000000000000084e91743124a982076C59f10084",
    chainId: "ethereum",
    name: "MEV Bot: Cross-DEX Arb",
    agentType: "MEV_BOT",
    score: 48,
    recommendation: "CAUTION",
    behavioralNarrative: "Multi-DEX arbitrage bot exploiting price differences between Uniswap, SushiSwap, and Curve. Atomic execution via Flashbots bundles.",
    financialSummary: { totalGasSpentETH: "345.6", netFlowETH: "+567.8" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.47 },
    protocolsUsed: ["Uniswap V3", "SushiSwap", "Curve", "Flashbots"],
    funFact: "Equalizes prices across DEXs — an involuntary public good.",
    anomalies: ["High-frequency cross-DEX arbitrage", "Revert rate: 28%"],
    txCount: 678901,
    lastActive: Date.now() - 3000,
    source: "seed",
  },
  {
    address: "0x6b75d8AF000000e20B7a7DDf000Ba900b4009A80",
    chainId: "ethereum",
    name: "MEV Bot: NFT Sniper",
    agentType: "MEV_BOT",
    score: 35,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "NFT mint sniping bot that front-runs public mints by detecting pending transactions. Hoards supply to resell at markup.",
    financialSummary: { totalGasSpentETH: "123.4", netFlowETH: "+456.7" },
    operationalPattern: { peakHoursUTC: [17, 18, 19, 20], consistencyScore: 0.33 },
    protocolsUsed: ["OpenSea", "Blur", "Flashbots"],
    funFact: "Sniped 200+ NFT mints in a single month during the 2024 NFT revival.",
    anomalies: ["NFT mint front-running detected", "Supply hoarding behavior"],
    txCount: 34567,
    lastActive: Date.now() - 50000,
    source: "seed",
  },
  {
    address: "0x00000000009726632680FB29d3F7A9734E3010E2",
    chainId: "ethereum",
    name: "Flashbots MEV-Share Searcher",
    agentType: "MEV_BOT",
    score: 57,
    recommendation: "CAUTION",
    behavioralNarrative: "MEV-Share participant that backruns transactions for arbitrage while sharing profits with users. Represents the 'ethical MEV' movement.",
    financialSummary: { totalGasSpentETH: "78.9", netFlowETH: "+134.5" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.55 },
    protocolsUsed: ["Flashbots", "MEV-Share", "Uniswap V3"],
    funFact: "Shares 90% of extracted MEV back with the users it backruns.",
    anomalies: ["MEV extraction via MEV-Share — partially redistributed"],
    txCount: 234567,
    lastActive: Date.now() - 7000,
    source: "seed",
  },
  {
    address: "0xDBF5E9c5206d0dB70a90108bf936DA60221dC080",
    chainId: "arbitrum",
    name: "MEV Bot: L2 Arbitrageur",
    agentType: "MEV_BOT",
    score: 41,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "L2-focused MEV bot exploiting Arbitrum's sequencer ordering. Takes advantage of FCFS ordering to front-run trades without Flashbots.",
    financialSummary: { totalGasSpentETH: "12.3", netFlowETH: "+89.4" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.38 },
    protocolsUsed: ["GMX", "Uniswap V3", "Camelot"],
    funFact: "Exploits Arbitrum's FCFS ordering — no Flashbots needed on L2.",
    anomalies: ["Sequencer ordering exploitation", "Front-running without MEV protection"],
    txCount: 456789,
    lastActive: Date.now() - 5000,
    source: "seed",
  },
  {
    address: "0x000000005736775Feb0C8568e7DEe77222a26880",
    chainId: "ethereum",
    name: "MEV Bot: Liquidation Searcher",
    agentType: "MEV_BOT",
    score: 46,
    recommendation: "CAUTION",
    behavioralNarrative: "Specialized MEV searcher focused on front-running liquidation transactions across lending protocols. Bundles liquidation with backrun arb.",
    financialSummary: { totalGasSpentETH: "156.7", netFlowETH: "+234.5" },
    operationalPattern: { peakHoursUTC: [2, 3, 8, 14], consistencyScore: 0.50 },
    protocolsUsed: ["Aave V3", "Compound V3", "Flashbots"],
    funFact: "Combines liquidation profits with the arbitrage created by the liquidation itself.",
    anomalies: ["Liquidation front-running via MEV bundles"],
    txCount: 89012,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0x3328F7f4A1D1C57c35df56bBf0c9dCAFCA309C49",
    chainId: "base",
    name: "MEV Bot: Base Sandwich",
    agentType: "MEV_BOT",
    score: 28,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Sandwich bot on Base exploiting the L2's growing DEX volume. Particularly targets large Aerodrome and Uniswap swaps.",
    financialSummary: { totalGasSpentETH: "2.3", netFlowETH: "+34.5" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.36 },
    protocolsUsed: ["Aerodrome", "Uniswap V3", "Base"],
    funFact: "Migrated from mainnet to Base — sandwich bots follow the volume.",
    anomalies: ["Sandwich attacks on Base DEXs", "Targeting Aerodrome liquidity"],
    txCount: 123456,
    lastActive: Date.now() - 4000,
    source: "seed",
  },
  {
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    chainId: "ethereum",
    name: "MEV Bot: Stablecoin Arb",
    agentType: "MEV_BOT",
    score: 54,
    recommendation: "CAUTION",
    behavioralNarrative: "Specialized arbitrageur exploiting stablecoin price deviations across Curve, Uniswap, and centralized exchanges. Helps maintain stablecoin pegs.",
    financialSummary: { totalGasSpentETH: "89.1", netFlowETH: "+123.4" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.60 },
    protocolsUsed: ["Curve", "Uniswap V3", "Maker PSM"],
    funFact: "Actually helps maintain stablecoin pegs — one of MEV's rare public goods.",
    anomalies: ["High-frequency stablecoin arbitrage"],
    txCount: 567890,
    lastActive: Date.now() - 8000,
    source: "seed",
  },

  // ─── DEX Traders ────────────────────────────────────────────────────────
  {
    address: "0x1111111254EEB25477B68fb85Ed929f73A960582",
    chainId: "ethereum",
    name: "1inch Aggregation Router V5",
    agentType: "DEX_TRADER",
    score: 93,
    recommendation: "SAFE",
    behavioralNarrative: "Major DEX aggregator routing trades across 50+ liquidity sources. Optimizes execution by splitting orders across multiple pools.",
    financialSummary: { totalGasSpentETH: "1891.2", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.93 },
    protocolsUsed: ["1inch", "Uniswap V3", "Curve", "Balancer"],
    funFact: "Routes through an average of 3.2 pools per trade for best execution.",
    anomalies: [],
    txCount: 3456789,
    lastActive: Date.now() - 2000,
    source: "seed",
  },
  {
    address: "0xDef1C0ded9bec7F1a1670819833240f027b25EfF",
    chainId: "ethereum",
    name: "0x Exchange Proxy",
    agentType: "DEX_TRADER",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "0x Protocol exchange proxy aggregating RFQ and AMM liquidity. Powers Matcha and many DeFi frontends with gasless limit orders.",
    financialSummary: { totalGasSpentETH: "923.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 19, 20], consistencyScore: 0.91 },
    protocolsUsed: ["0x Protocol", "Uniswap V3", "Curve"],
    funFact: "Supports gasless limit orders — users trade without paying gas.",
    anomalies: [],
    txCount: 2891023,
    lastActive: Date.now() - 9000,
    source: "seed",
  },
  {
    address: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
    chainId: "ethereum",
    name: "Uniswap V3 SwapRouter",
    agentType: "DEX_TRADER",
    score: 96,
    recommendation: "SAFE",
    behavioralNarrative: "Core Uniswap V3 routing contract. Processes single-hop and multi-hop swaps with concentrated liquidity. The heartbeat of onchain trading.",
    financialSummary: { totalGasSpentETH: "4521.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.96 },
    protocolsUsed: ["Uniswap V3"],
    funFact: "Has facilitated over $1T in cumulative swap volume.",
    anomalies: [],
    txCount: 12345678,
    lastActive: Date.now() - 1000,
    source: "seed",
  },
  {
    address: "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD",
    chainId: "ethereum",
    name: "Uniswap Universal Router",
    agentType: "DEX_TRADER",
    score: 95,
    recommendation: "SAFE",
    behavioralNarrative: "Unified routing contract supporting ERC-20 swaps, NFT purchases, and multi-step DeFi actions in a single transaction. The Swiss Army knife of DeFi routers.",
    financialSummary: { totalGasSpentETH: "3456.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.95 },
    protocolsUsed: ["Uniswap V3", "Uniswap Universal Router"],
    funFact: "Can swap tokens AND buy an NFT in a single atomic transaction.",
    anomalies: [],
    txCount: 8901234,
    lastActive: Date.now() - 1000,
    source: "seed",
  },
  {
    address: "0xBA12222222228d8Ba445958a75a0704d566BF2C8",
    chainId: "ethereum",
    name: "Balancer V2 Vault",
    agentType: "DEX_TRADER",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "Single-vault architecture holding all Balancer pool assets. Enables flash swaps, internal balances, and gas-efficient multi-hop routing.",
    financialSummary: { totalGasSpentETH: "1234.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.92 },
    protocolsUsed: ["Balancer V2"],
    funFact: "Holds $2B+ in a single vault contract — one of the largest smart contracts by TVL.",
    anomalies: [],
    txCount: 2345678,
    lastActive: Date.now() - 5000,
    source: "seed",
  },
  {
    address: "0x9008D19f58AAbD9eD0D60971565AA8510560ab41",
    chainId: "ethereum",
    name: "CoW Protocol Settlement",
    agentType: "DEX_TRADER",
    score: 89,
    recommendation: "SAFE",
    behavioralNarrative: "Batch auction DEX that matches Coincidence of Wants (CoW) before routing to AMMs. Protects users from MEV by design.",
    financialSummary: { totalGasSpentETH: "567.8", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.90 },
    protocolsUsed: ["CoW Protocol", "CoW Swap"],
    funFact: "30% of trades are matched peer-to-peer — zero AMM fees, zero MEV.",
    anomalies: [],
    txCount: 1234567,
    lastActive: Date.now() - 3000,
    source: "seed",
  },
  {
    address: "0xDEF171Fe48CF0115B1d80b88dc8eAB59176FEe57",
    chainId: "ethereum",
    name: "ParaSwap Augustus V6",
    agentType: "DEX_TRADER",
    score: 87,
    recommendation: "SAFE",
    behavioralNarrative: "DEX aggregator with delta algorithm splitting trades across pools for optimal execution. Supports limit orders and DCA strategies.",
    financialSummary: { totalGasSpentETH: "678.9", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 19], consistencyScore: 0.88 },
    protocolsUsed: ["ParaSwap", "Uniswap V3", "Curve"],
    funFact: "Its delta algorithm tests 1000+ routing paths per trade in milliseconds.",
    anomalies: [],
    txCount: 1567890,
    lastActive: Date.now() - 7000,
    source: "seed",
  },
  {
    address: "0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552",
    chainId: "ethereum",
    name: "Curve Router V1 (Deprecated)",
    agentType: "DEX_TRADER",
    score: 55,
    recommendation: "CAUTION",
    behavioralNarrative: "Deprecated Curve router still receiving traffic. Users should migrate to V2 — this version lacks the latest security patches from the July 2023 reentrancy fix.",
    financialSummary: { totalGasSpentETH: "2345.6", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.94 },
    protocolsUsed: ["Curve Finance"],
    funFact: "Still gets traffic despite being deprecated — old integrations die hard.",
    anomalies: ["Deprecated contract — missing post-exploit security patches"],
    txCount: 4567890,
    lastActive: Date.now() - 2000,
    source: "seed",
  },
  {
    address: "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5",
    chainId: "ethereum",
    name: "KyberSwap Aggregator",
    agentType: "DEX_TRADER",
    score: 63,
    recommendation: "CAUTION",
    behavioralNarrative: "DEX aggregator with elastic pool technology. Suffered a major exploit in November 2023 but has since rebuilt with improved security.",
    financialSummary: { totalGasSpentETH: "456.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.78 },
    protocolsUsed: ["KyberSwap", "KyberDMM"],
    funFact: "Rebuilt from scratch after a $48M exploit — now with multi-audit security.",
    anomalies: ["Historical exploit: $48M stolen in Nov 2023"],
    txCount: 890123,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43",
    chainId: "arbitrum",
    name: "Camelot V3 Router (Arbitrum)",
    agentType: "DEX_TRADER",
    score: 84,
    recommendation: "SAFE",
    behavioralNarrative: "Arbitrum-native DEX with concentrated liquidity and custom fee tiers. Dominates native Arbitrum token trading pairs.",
    financialSummary: { totalGasSpentETH: "23.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.85 },
    protocolsUsed: ["Camelot", "Arbitrum"],
    funFact: "The go-to DEX for new Arbitrum token launches — gets 60% of first-day volume.",
    anomalies: [],
    txCount: 567890,
    lastActive: Date.now() - 8000,
    source: "seed",
  },
  {
    address: "0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb8743e2",
    chainId: "base",
    name: "Aerodrome Finance Router",
    agentType: "DEX_TRADER",
    score: 88,
    recommendation: "SAFE",
    behavioralNarrative: "Base's dominant DEX using the ve(3,3) model. Handles the majority of on-chain trading volume on Base with vote-escrowed tokenomics.",
    financialSummary: { totalGasSpentETH: "12.3", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.89 },
    protocolsUsed: ["Aerodrome", "Base"],
    funFact: "Captured 60% of Base DEX volume within 3 months of launch.",
    anomalies: [],
    txCount: 1234567,
    lastActive: Date.now() - 3000,
    source: "seed",
  },

  // ─── Governance ─────────────────────────────────────────────────────────
  {
    address: "0xc0Da02939E1441F497fd74F78cE7Decb17B66529",
    chainId: "ethereum",
    name: "Compound Governor Bravo",
    agentType: "GOVERNANCE",
    score: 94,
    recommendation: "SAFE",
    behavioralNarrative: "Compound's on-chain governance contract executing community proposals. The template that most DeFi governance systems are forked from.",
    financialSummary: { totalGasSpentETH: "23.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [15, 16, 17, 18], consistencyScore: 0.82 },
    protocolsUsed: ["Compound", "Governor Bravo"],
    funFact: "The most forked governance contract in DeFi — used by 50+ protocols.",
    anomalies: [],
    txCount: 4567,
    lastActive: Date.now() - 300000,
    source: "seed",
  },
  {
    address: "0xEC568fffba86c094cf06b22134B23074DFE2252c",
    chainId: "ethereum",
    name: "Aave Governance V3",
    agentType: "GOVERNANCE",
    score: 93,
    recommendation: "SAFE",
    behavioralNarrative: "Cross-chain governance system executing proposals across Ethereum, Polygon, Avalanche, and Arbitrum. Votes on mainnet, executes everywhere.",
    financialSummary: { totalGasSpentETH: "34.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.80 },
    protocolsUsed: ["Aave", "Aave Governance"],
    funFact: "Executes governance proposals on 4 chains simultaneously from a single vote.",
    anomalies: [],
    txCount: 2345,
    lastActive: Date.now() - 400000,
    source: "seed",
  },
  {
    address: "0x323A76393544d5ecca80cd6ef2A560C6a395b7E3",
    chainId: "ethereum",
    name: "ENS Governor",
    agentType: "GOVERNANCE",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "ENS DAO governance contract managing the Ethereum Name Service treasury and protocol parameters. High community participation rates.",
    financialSummary: { totalGasSpentETH: "12.3", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [15, 16, 17], consistencyScore: 0.78 },
    protocolsUsed: ["ENS", "ENS DAO"],
    funFact: "Controls a $1B+ treasury — one of the largest DAO treasuries in crypto.",
    anomalies: [],
    txCount: 1234,
    lastActive: Date.now() - 500000,
    source: "seed",
  },
  {
    address: "0x408ED6354d4973f66138C91495F2f2FCbd8724C3",
    chainId: "ethereum",
    name: "Uniswap Governor Bravo",
    agentType: "GOVERNANCE",
    score: 92,
    recommendation: "SAFE",
    behavioralNarrative: "Uniswap DAO governance executing protocol fee switches, grant programs, and treasury allocations. Whale-dominated but transparent.",
    financialSummary: { totalGasSpentETH: "18.9", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [15, 16, 17, 18], consistencyScore: 0.76 },
    protocolsUsed: ["Uniswap", "Governor Bravo"],
    funFact: "A single proposal to activate the fee switch took 2 years of debate.",
    anomalies: [],
    txCount: 890,
    lastActive: Date.now() - 450000,
    source: "seed",
  },
  {
    address: "0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2",
    chainId: "ethereum",
    name: "Safe (Gnosis Safe) Proxy Factory",
    agentType: "GOVERNANCE",
    score: 95,
    recommendation: "SAFE",
    behavioralNarrative: "Factory contract deploying multisig wallets used by virtually every DAO and protocol treasury. The backbone of on-chain governance execution.",
    financialSummary: { totalGasSpentETH: "345.6", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.91 },
    protocolsUsed: ["Safe", "Gnosis Safe"],
    funFact: "Secures over $100B in assets across 8M+ deployed Safe wallets.",
    anomalies: [],
    txCount: 2345678,
    lastActive: Date.now() - 3000,
    source: "seed",
  },
  {
    address: "0xDe30da39c46104798bB5aA3fe8B9e0e1F348163F",
    chainId: "ethereum",
    name: "Gitcoin Governor",
    agentType: "GOVERNANCE",
    score: 86,
    recommendation: "SAFE",
    behavioralNarrative: "Gitcoin DAO governance managing public goods funding rounds and treasury allocations. Active community with regular quarterly proposals.",
    financialSummary: { totalGasSpentETH: "8.9", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [15, 16, 17], consistencyScore: 0.74 },
    protocolsUsed: ["Gitcoin", "Gitcoin Grants"],
    funFact: "Has funded over $50M in public goods through quadratic funding rounds.",
    anomalies: [],
    txCount: 567,
    lastActive: Date.now() - 600000,
    source: "seed",
  },
  {
    address: "0x6f3E6272A167e8AcCb32072d08E0957F9c79223d",
    chainId: "ethereum",
    name: "Nouns DAO Treasury",
    agentType: "GOVERNANCE",
    score: 87,
    recommendation: "SAFE",
    behavioralNarrative: "Nouns DAO governance executing proposals funded by daily noun auctions. One of the most active on-chain governance systems with daily revenue.",
    financialSummary: { totalGasSpentETH: "45.6", netFlowETH: "-12345.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.85 },
    protocolsUsed: ["Nouns DAO", "Nouns Auction"],
    funFact: "Generates revenue every 24 hours from a single NFT auction — forever.",
    anomalies: [],
    txCount: 3456,
    lastActive: Date.now() - 250000,
    source: "seed",
  },
  {
    address: "0xbE286431454714F511008713973d3B053A2d38f3",
    chainId: "ethereum",
    name: "MakerDAO Governance (Chief)",
    agentType: "GOVERNANCE",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "MakerDAO's executive voting contract where MKR holders stake tokens to approve governance actions. Controls $8B+ in DAI parameters.",
    financialSummary: { totalGasSpentETH: "56.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16], consistencyScore: 0.83 },
    protocolsUsed: ["MakerDAO", "DSChief"],
    funFact: "A single governance vote controls interest rates for billions in DAI loans.",
    anomalies: [],
    txCount: 12345,
    lastActive: Date.now() - 350000,
    source: "seed",
  },
  {
    address: "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9",
    chainId: "arbitrum",
    name: "Arbitrum DAO Governor",
    agentType: "GOVERNANCE",
    score: 89,
    recommendation: "SAFE",
    behavioralNarrative: "Arbitrum DAO governance executing proposals for the L2 ecosystem. Manages the $4B ARB treasury with community-elected delegates.",
    financialSummary: { totalGasSpentETH: "2.3", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [15, 16, 17, 18], consistencyScore: 0.81 },
    protocolsUsed: ["Arbitrum DAO", "Tally"],
    funFact: "One of the largest DAO treasuries — $4B in ARB tokens at peak.",
    anomalies: [],
    txCount: 678,
    lastActive: Date.now() - 200000,
    source: "seed",
  },
  {
    address: "0x0BEF27FEB58e857046d630B2c03dFb7bae567494",
    chainId: "optimism",
    name: "Optimism Governor",
    agentType: "GOVERNANCE",
    score: 88,
    recommendation: "SAFE",
    behavioralNarrative: "Optimism Collective governance with dual-house system (Token House + Citizens House). Pioneering retroactive public goods funding.",
    financialSummary: { totalGasSpentETH: "1.2", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [15, 16, 17], consistencyScore: 0.79 },
    protocolsUsed: ["Optimism", "Optimism Governance"],
    funFact: "First DAO with a bicameral governance system — Token House and Citizens House.",
    anomalies: [],
    txCount: 456,
    lastActive: Date.now() - 350000,
    source: "seed",
  },

  // ─── Yield Optimizers ───────────────────────────────────────────────────
  {
    address: "0xa258C4606Ca8206D8aA700cE2143D7db854D168c",
    chainId: "ethereum",
    name: "Yearn V3 Vault Factory",
    agentType: "YIELD_OPTIMIZER",
    score: 88,
    recommendation: "SAFE",
    behavioralNarrative: "Yearn's V3 vault infrastructure deploying automated yield strategies. Each vault runs multiple strategies simultaneously, auto-compounding returns.",
    financialSummary: { totalGasSpentETH: "234.5", netFlowETH: "+12.3" },
    operationalPattern: { peakHoursUTC: [6, 12, 18, 0], consistencyScore: 0.91 },
    protocolsUsed: ["Yearn Finance", "Yearn V3"],
    funFact: "Yearn V3 vaults can run 20 strategies simultaneously — auto-rebalancing between them.",
    anomalies: [],
    txCount: 345678,
    lastActive: Date.now() - 10000,
    source: "seed",
  },
  {
    address: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31",
    chainId: "ethereum",
    name: "Convex Finance Booster",
    agentType: "YIELD_OPTIMIZER",
    score: 90,
    recommendation: "SAFE",
    behavioralNarrative: "Curve yield booster aggregating veCRV voting power to maximize Curve farming rewards. Deposits are staked in Curve gauges with boosted CRV emissions.",
    financialSummary: { totalGasSpentETH: "456.7", netFlowETH: "+89.1" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.94 },
    protocolsUsed: ["Convex Finance", "Curve Finance"],
    funFact: "Controls more veCRV voting power than Curve's own team.",
    anomalies: [],
    txCount: 567890,
    lastActive: Date.now() - 5000,
    source: "seed",
  },
  {
    address: "0x0De4Bf93Be3a75D9ee6e6d0B5e7EcAEbB4Da0300",
    chainId: "ethereum",
    name: "Pendle Router V4",
    agentType: "YIELD_OPTIMIZER",
    score: 86,
    recommendation: "SAFE",
    behavioralNarrative: "Yield tokenization protocol splitting yield-bearing tokens into principal and yield components. Enables fixed-rate yields and yield speculation.",
    financialSummary: { totalGasSpentETH: "123.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.87 },
    protocolsUsed: ["Pendle Finance"],
    funFact: "Created a $5B market for trading future yield — a DeFi primitive that didn't exist before.",
    anomalies: [],
    txCount: 456789,
    lastActive: Date.now() - 7000,
    source: "seed",
  },
  {
    address: "0x858646372CC42E1A627fcE94aa7A7033e7CF075A",
    chainId: "ethereum",
    name: "EigenLayer StrategyManager",
    agentType: "YIELD_OPTIMIZER",
    score: 83,
    recommendation: "SAFE",
    behavioralNarrative: "Restaking protocol allowing ETH stakers to secure additional services (AVSs) for extra yield. Manages strategy deposits and withdrawal queues.",
    financialSummary: { totalGasSpentETH: "567.8", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.86 },
    protocolsUsed: ["EigenLayer"],
    funFact: "Attracted $15B in restaked ETH within 6 months of launch.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 8000,
    source: "seed",
  },
  {
    address: "0xFe7E862068B02C6295ea09089e39Ad2D5b8E8aF0",
    chainId: "ethereum",
    name: "Lido Staking Router",
    agentType: "YIELD_OPTIMIZER",
    score: 93,
    recommendation: "SAFE",
    behavioralNarrative: "Routes ETH staking deposits to Lido's curated set of node operators. Manages the largest liquid staking pool on Ethereum.",
    financialSummary: { totalGasSpentETH: "234.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.95 },
    protocolsUsed: ["Lido", "Lido Staking"],
    funFact: "Routes 32% of all staked ETH — the single largest staking entity.",
    anomalies: [],
    txCount: 345678,
    lastActive: Date.now() - 4000,
    source: "seed",
  },
  {
    address: "0xDD9683a9a44016B212AF5c54Da9e3e498Ec8D700",
    chainId: "ethereum",
    name: "Rocket Pool Minipool Manager",
    agentType: "YIELD_OPTIMIZER",
    score: 89,
    recommendation: "SAFE",
    behavioralNarrative: "Decentralized staking protocol creating minipools that pair 16 ETH from depositors with 16 ETH from node operators. Most decentralized staking option.",
    financialSummary: { totalGasSpentETH: "123.4", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.90 },
    protocolsUsed: ["Rocket Pool"],
    funFact: "Anyone can run a node with just 8 ETH — the lowest barrier to solo staking.",
    anomalies: [],
    txCount: 89012,
    lastActive: Date.now() - 20000,
    source: "seed",
  },
  {
    address: "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
    chainId: "ethereum",
    name: "Aura Finance Depositor",
    agentType: "YIELD_OPTIMIZER",
    score: 85,
    recommendation: "SAFE",
    behavioralNarrative: "Balancer yield booster aggregating veBAL voting power. The Convex-equivalent for Balancer — deposits earn boosted BAL emissions.",
    financialSummary: { totalGasSpentETH: "67.8", netFlowETH: "+12.3" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.88 },
    protocolsUsed: ["Aura Finance", "Balancer V2"],
    funFact: "What Convex did for Curve, Aura does for Balancer — same playbook, different pool.",
    anomalies: [],
    txCount: 123456,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0x5aB0ffB2e65624E6cdedD1E8e9fA755eB01CE4ec",
    chainId: "arbitrum",
    name: "Beefy Vault (Arbitrum)",
    agentType: "YIELD_OPTIMIZER",
    score: 79,
    recommendation: "SAFE",
    behavioralNarrative: "Multi-chain auto-compounder deploying yield strategies across Arbitrum DeFi. Auto-harvests and reinvests rewards every few hours.",
    financialSummary: { totalGasSpentETH: "4.5", netFlowETH: "+0.8" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.85 },
    protocolsUsed: ["Beefy Finance", "GMX", "Camelot"],
    funFact: "Auto-compounds 500+ strategies across 20 chains — the most multi-chain yield optimizer.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 12000,
    source: "seed",
  },
  {
    address: "0x2b2C81e08f1Af8835a78Bb2A90AE924ACE0eA4bE",
    chainId: "base",
    name: "Moonwell Yield Agent (Base)",
    agentType: "YIELD_OPTIMIZER",
    score: 76,
    recommendation: "SAFE",
    behavioralNarrative: "Automated lending optimizer on Base depositing into Moonwell markets for yield. Rebalances between supply markets based on utilization rates.",
    financialSummary: { totalGasSpentETH: "0.9", netFlowETH: "+0.3" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.81 },
    protocolsUsed: ["Moonwell", "Base"],
    funFact: "Moves funds between Moonwell markets every 4 hours chasing the best APY.",
    anomalies: [],
    txCount: 45678,
    lastActive: Date.now() - 25000,
    source: "seed",
  },
  {
    address: "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45",
    chainId: "ethereum",
    name: "Sommelier Cellar Router",
    agentType: "YIELD_OPTIMIZER",
    score: 66,
    recommendation: "CAUTION",
    behavioralNarrative: "AI-driven yield vaults using off-chain strategist models to manage on-chain positions. Strategies are proposed off-chain and executed via governance.",
    financialSummary: { totalGasSpentETH: "34.5", netFlowETH: "+5.6" },
    operationalPattern: { peakHoursUTC: [14, 15, 16], consistencyScore: 0.72 },
    protocolsUsed: ["Sommelier", "Cosmos"],
    funFact: "Strategy decisions are made by AI models but require on-chain governance approval.",
    anomalies: ["Off-chain strategy computation — limited on-chain transparency"],
    txCount: 34567,
    lastActive: Date.now() - 45000,
    source: "seed",
  },
  {
    address: "0x6F55Da7a2ee04E80cF3bCd6a0B56b7dC8B93F40b",
    chainId: "polygon",
    name: "Beefy Vault (Polygon)",
    agentType: "YIELD_OPTIMIZER",
    score: 77,
    recommendation: "SAFE",
    behavioralNarrative: "Beefy auto-compounder on Polygon optimizing QuickSwap and Aave yields. High-frequency harvest cycles thanks to Polygon's low gas costs.",
    financialSummary: { totalGasSpentETH: "0.3", netFlowETH: "+0.1" },
    operationalPattern: { peakHoursUTC: [0, 4, 8, 12, 16, 20], consistencyScore: 0.83 },
    protocolsUsed: ["Beefy Finance", "QuickSwap", "Aave V3"],
    funFact: "Harvests rewards every 30 minutes on Polygon — 48 times per day.",
    anomalies: [],
    txCount: 345678,
    lastActive: Date.now() - 9000,
    source: "seed",
  },
  {
    address: "0x1F98431c8aD98523631AE4a59f267346ea31F984",
    chainId: "ethereum",
    name: "Uniswap V3 Factory",
    agentType: "DEX_TRADER",
    score: 97,
    recommendation: "SAFE",
    behavioralNarrative: "Core factory contract deploying Uniswap V3 pools. Every concentrated liquidity pool on Uniswap originates from this contract.",
    financialSummary: { totalGasSpentETH: "1234.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.97 },
    protocolsUsed: ["Uniswap V3"],
    funFact: "Has deployed over 15,000 unique trading pools since launch.",
    anomalies: [],
    txCount: 5678901,
    lastActive: Date.now() - 1000,
    source: "seed",
  },
  {
    address: "0x99a58482BD75cbab83b27EC03CA68fF489b5788f",
    chainId: "gnosis",
    name: "CowSwap Solver (Gnosis)",
    agentType: "DEX_TRADER",
    score: 82,
    recommendation: "SAFE",
    behavioralNarrative: "CoW Protocol solver on Gnosis Chain executing batch auctions. Native xDAI gas costs make even tiny trades economically viable.",
    financialSummary: { totalGasSpentETH: "0.5", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.84 },
    protocolsUsed: ["CoW Protocol", "Gnosis Chain"],
    funFact: "Batch settlement on Gnosis costs less than a single swap on mainnet.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 15000,
    source: "seed",
  },
  {
    address: "0x4e3FBD56CD56c3e72c1403e103b45Db9da5B9D2B",
    chainId: "ethereum",
    name: "Convex CVX Staking",
    agentType: "YIELD_OPTIMIZER",
    score: 87,
    recommendation: "SAFE",
    behavioralNarrative: "CVX token staking contract distributing platform revenue to locked CVX holders. Central to the Curve Wars meta-game.",
    financialSummary: { totalGasSpentETH: "89.1", netFlowETH: "+23.4" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.92 },
    protocolsUsed: ["Convex Finance", "Curve Finance"],
    funFact: "vlCVX holders control $4B+ in Curve gauge emissions — the Curve Wars kingmaker.",
    anomalies: [],
    txCount: 234567,
    lastActive: Date.now() - 8000,
    source: "seed",
  },
  {
    address: "0xC36442b4a4522E871399CD717aBDD847Ab11FE88",
    chainId: "ethereum",
    name: "Uniswap V3 NonfungiblePositionManager",
    agentType: "DEX_TRADER",
    score: 94,
    recommendation: "SAFE",
    behavioralNarrative: "Manages concentrated liquidity positions as NFTs. Every LP position on Uniswap V3 is minted, modified, and burned through this contract.",
    financialSummary: { totalGasSpentETH: "2345.6", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.95 },
    protocolsUsed: ["Uniswap V3"],
    funFact: "Each LP position is a unique NFT — there are 5M+ Uniswap V3 position NFTs.",
    anomalies: [],
    txCount: 6789012,
    lastActive: Date.now() - 1000,
    source: "seed",
  },
  {
    address: "0x83E9115d334D248Ce39a6f36144aEaB5b3456e75",
    chainId: "gnosis",
    name: "Gnosis DAO Safe",
    agentType: "GOVERNANCE",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "Primary Gnosis DAO multisig managing protocol treasury and ecosystem grants. Executes community-approved proposals with 5-of-8 threshold.",
    financialSummary: { totalGasSpentETH: "1.2", netFlowETH: "-234.5" },
    operationalPattern: { peakHoursUTC: [14, 15, 16], consistencyScore: 0.77 },
    protocolsUsed: ["Gnosis DAO", "Safe"],
    funFact: "One of the few DAOs that operates on its own chain — Gnosis governing Gnosis.",
    anomalies: [],
    txCount: 890,
    lastActive: Date.now() - 400000,
    source: "seed",
  },
  {
    address: "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B",
    chainId: "ethereum",
    name: "Compound Comptroller",
    agentType: "LIQUIDATOR",
    score: 80,
    recommendation: "SAFE",
    behavioralNarrative: "Risk management contract for Compound V2 controlling collateral factors and liquidation incentives. Core protocol safety infrastructure.",
    financialSummary: { totalGasSpentETH: "345.6", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.90 },
    protocolsUsed: ["Compound V2"],
    funFact: "Set the standard for lending protocol risk parameters — most forks copy its values.",
    anomalies: [],
    txCount: 567890,
    lastActive: Date.now() - 50000,
    source: "seed",
  },
  {
    address: "0xAB594600376Ec9fD91F8e8dC9E1bAe62174b8362",
    chainId: "polygon",
    name: "Chainlink MATIC/USD Polygon",
    agentType: "ORACLE",
    score: 92,
    recommendation: "SAFE",
    behavioralNarrative: "Native MATIC/USD price feed on Polygon securing lending and derivatives protocols. Critical infrastructure for Polygon DeFi ecosystem.",
    financialSummary: { totalGasSpentETH: "0.9", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [0, 6, 12, 18], consistencyScore: 0.97 },
    protocolsUsed: ["Chainlink", "Polygon"],
    funFact: "The most queried oracle on Polygon — called more than ETH/USD on mainnet.",
    anomalies: [],
    txCount: 789012,
    lastActive: Date.now() - 4000,
    source: "seed",
  },
  {
    address: "0x32400084C286CF3E17e7B677ea9583e60a000324",
    chainId: "ethereum",
    name: "zkSync Era Diamond Proxy",
    agentType: "BRIDGE_RELAYER",
    score: 91,
    recommendation: "SAFE",
    behavioralNarrative: "zkSync Era's main L1 contract handling deposits, withdrawals, and ZK proof verification. Core rollup infrastructure with cryptographic validity proofs.",
    financialSummary: { totalGasSpentETH: "3456.7", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 17], consistencyScore: 0.94 },
    protocolsUsed: ["zkSync Era", "Matter Labs"],
    funFact: "Verifies zero-knowledge proofs for millions of L2 transactions in a single L1 tx.",
    anomalies: [],
    txCount: 1234567,
    lastActive: Date.now() - 2000,
    source: "seed",
  },
  {
    address: "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
    chainId: "ethereum",
    name: "Synthetix Proxy",
    agentType: "YIELD_OPTIMIZER",
    score: 81,
    recommendation: "SAFE",
    behavioralNarrative: "Synthetix staking and synth minting proxy. SNX stakers mint sUSD and earn trading fees from the protocol's derivatives exchange.",
    financialSummary: { totalGasSpentETH: "567.8", netFlowETH: "+34.5" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.84 },
    protocolsUsed: ["Synthetix"],
    funFact: "Stakers collectively act as counterparty to every synth trade — shared risk, shared reward.",
    anomalies: [],
    txCount: 1234567,
    lastActive: Date.now() - 10000,
    source: "seed",
  },
  {
    address: "0x8dBdb5C03d8aDc62ca20B43e2Dd3a3E4d1a8d33C",
    chainId: "base",
    name: "Seamless Protocol Optimizer",
    agentType: "YIELD_OPTIMIZER",
    score: 38,
    recommendation: "BLOCKLIST",
    behavioralNarrative: "Integrated lending optimizer on Base auto-leveraging positions for amplified yield. Higher risk profile due to recursive borrowing strategies.",
    financialSummary: { totalGasSpentETH: "0.4", netFlowETH: "+0.2" },
    operationalPattern: { peakHoursUTC: [10, 14, 15, 20], consistencyScore: 0.75 },
    protocolsUsed: ["Seamless Protocol", "Base"],
    funFact: "Auto-leverages up to 3x on stablecoin yields — higher risk, higher reward.",
    anomalies: ["Recursive borrowing strategy — amplified liquidation risk", "Unaudited leverage loop — no circuit breaker on max leverage"],
    txCount: 23456,
    lastActive: Date.now() - 20000,
    source: "seed",
  },
  {
    address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
    chainId: "ethereum",
    name: "Uniswap V2 Router",
    agentType: "DEX_TRADER",
    score: 85,
    recommendation: "SAFE",
    behavioralNarrative: "Legacy Uniswap V2 router still processing significant volume. Simpler constant-product AMM preferred by some MEV bots and older integrations.",
    financialSummary: { totalGasSpentETH: "5678.9", netFlowETH: "+0.0" },
    operationalPattern: { peakHoursUTC: [14, 15, 16, 20], consistencyScore: 0.93 },
    protocolsUsed: ["Uniswap V2"],
    funFact: "Still processes $100M+ daily despite V3 being live for 3 years.",
    anomalies: [],
    txCount: 23456789,
    lastActive: Date.now() - 1000,
    source: "seed",
  },
  {
    address: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
    chainId: "ethereum",
    name: "vitalik.eth (Governance Participant)",
    agentType: "GOVERNANCE",
    score: 96,
    recommendation: "SAFE",
    behavioralNarrative: "Ethereum co-founder's public address participating in protocol governance, charitable donations, and ecosystem grants. Highly visible on-chain activity.",
    financialSummary: { totalGasSpentETH: "89.1", netFlowETH: "-12345.6" },
    operationalPattern: { peakHoursUTC: [6, 7, 14, 15], consistencyScore: 0.65 },
    protocolsUsed: ["ENS", "Gitcoin", "Various DAOs"],
    funFact: "Donated $1B+ in SHIB tokens to India's COVID relief fund in 2021.",
    anomalies: [],
    txCount: 4567,
    lastActive: Date.now() - 100000,
    source: "seed",
  },
] as const;

/** Mapping from AgentType to display name */
export const AGENT_TYPE_LABELS: Record<string, string> = {
  KEEPER: "Keepers",
  ORACLE: "Oracles",
  BRIDGE_RELAYER: "Bridge Relayers",
  LIQUIDATOR: "Liquidators",
  MEV_BOT: "MEV Bots",
  DEX_TRADER: "DEX Traders",
  GOVERNANCE: "Governance",
  YIELD_OPTIMIZER: "Yield Optimizer",
  UNKNOWN: "Unknown",
};

/** Mapping from AgentType to donut/label color */
export const AGENT_TYPE_COLORS: Record<string, string> = {
  KEEPER: "#22c55e",
  ORACLE: "#6ea8fe",
  BRIDGE_RELAYER: "#9070d4",
  LIQUIDATOR: "#eab308",
  MEV_BOT: "#ef4444",
  DEX_TRADER: "#a8a29e",
  GOVERNANCE: "#60a5fa",
  YIELD_OPTIMIZER: "#34d399",
  UNKNOWN: "#525252",
};
